In [1]:
from ast import Lambda
import tensorflow as tf
import json

import os
import numpy as np
import cv2
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

In [2]:
yolo_anchors = np.array([(10, 13), (16, 30), (33, 23), (30, 61), (62, 45),
                         (59, 119), (116, 90), (156, 198), (373, 326)],
                        np.float32) / (10, 13)

In [3]:
yolo_anchors

array([[ 1.        ,  1.        ],
       [ 1.6       ,  2.30769231],
       [ 3.3       ,  1.76923077],
       [ 3.        ,  4.69230769],
       [ 6.2       ,  3.46153846],
       [ 5.9       ,  9.15384615],
       [11.6       ,  6.92307692],
       [15.6       , 15.23076923],
       [37.3       , 25.07692308]])

In [108]:
t = tf.constant([1, 2, 3, 4, 9])
t

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 9])>

In [109]:
t12, t34, classes = tf.split(t, (2, 2, 1), -1)
t12, t34, classes

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([9])>)

In [110]:
t[..., 0:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [111]:
t12 = tf.reverse(t[..., 0:2], axis=(-1,))
t12

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1])>

In [112]:
t34 = tf.reverse(t[..., 2:4], axis=(-1, ))
t34

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3])>

In [113]:
t[..., -1:]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9])>

In [114]:
t = tf.concat([t12, t34, t[..., -1:]], axis=-1)
t

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 1, 4, 3, 9])>